<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST" Id="{bd0cd056-c9be-07e2-1020-9a5696ebe527}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR	
	FB_Beckhoff_EL5152_Test : FB_Beckhoff_EL5152_Test;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>